target = "http://localhost:8000/api/chat"
concurrency = 8
timeout_ms = 60000
prompts = "data/prompts.csv"
out = "report.jsonl"

# "pattern", "llm", or "hybrid"
detection_method = "hybrid"

mock_mode = true
